# Generated by Django 4.2.7 on 2023-11-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_date',
            new_name='create_date',
        ),
    ]
